modal:
  gpu: L40S
  timeout: 1800

model:
  name: "EleutherAI/pythia-14m"

data:
  train_path: "/data/"

train:
  save_interval: 1000
  log_interval: 1
  global_batch_size: 512
  micro_batch_size: 4
  max_tokens: 1000000
  max_norm: 1.0
  min_lr: 4e-5
  lr_warmup_steps: 2000
  tie_embeddings: False

eval:
  interval: 1000
  max_iters: 10

log:
  project: "SPAR Algorithmic Progress"
  run: "Test run"
  group: "Test"
